# Generated by Django 4.1.7 on 2023-03-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='slug',
            field=models.SlugField(verbose_name='URL'),
        ),
    ]
