# Generated by Django 4.1.7 on 2023-03-14 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='user',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='slug',
            field=models.SlugField(verbose_name='URL'),
        ),
    ]
